apiVersion: apps/v1
kind: Deployment
metadata:
  name: hi-name
spec:
  selector:
    matchLabels:
      app:  hi-name
  template:
    metadata:
      labels:
        app:  hi-name
    spec:
      containers:
      - name:  hi-name
        image: felipepereiracg/hi-name:{{tag}}
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hi-name
spec:
  selector:
    app: hi-name
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer